pelican:
  notify:         notifications@infra.apache.org
  autobuild:      true
  target:         asf-site
  whoami:         master
  
staging:
  whoami: asf-break-test
  profile: ~

github:
  description:   Infrastructure Website Repository...

notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               issues@infra.apache.org
