pelican:
  notify:         notifications@infra.apache.org
  autobuild:      preview/*
  target:         asf-site
  whoami:         master
  
staging:
  whoami: asf-break-test
  profile: ~

github:
  description:   Infrastructure Team Website Repository
  homepage:      https://infra.apache.org
  collaborators:
   - Humbedooh1
   - Humbedooh2
   - Humbedooh3
   - Humbedooh4
   - Humbedooh5
   - Humbedooh6
   - Humbedooh7
   - Humbedooh8
   - Humbedooh9
   - Humbedooh10
   - Humbedooh11
   - Humbedooh12
   - Humbedooh13
   - Humbedooh14
   - Humbedooh15
   - Humbedooh16
   - Humbedooh17
   - Humbedooh18
   - Humbedooh19
   - Humbedooh20
   - Humbedooh21
   - Humbedooh22

notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               issues@infra.apache.org
