name: Build a Pelican Website
on:
  push:
    branches: [ "dfoulks/pelfix" ]
  workflow_dispatch:
jobs:
  build-pelican:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'dfoulks/pelfix'
      - uses: apache/infrastructure-actions/pelican@dfoulks/pelfix
        with:
          destination: 'asf-site-pelfix'
          gfm: 'true'
