name: Build a Pelican Website
on:
  push:
    branches: [ "dfoulks/pelican_gha" ]
  pull_request:
    branches: [ "dfoulks/pelican_gha" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ''
          ref: 'dfoulks/pelican_gha'
      - name: Install Pelican
        run: sudo pip install pelican markdown ghp-import
      - name: Run a one-line script
        run: python3 -m pelican content -o output
        working-directory: '/home/runner/work/infrastructure-website/infrastructure-website'
